/*This file tests the following error:

[1] Mismatch between actual parameters at a call site
    and the definition of the called procedure

Note: There are multiple ways in which the
above error is tested in this file */


 const b: [2; char] = [' ', ' '];

  fn A(a: int) {
       let x= 0;

     x = A(B(100)); /* Function B is of type Character but parameter to A is of type integer */
    }

    fn B(a: int): char {
      let d = 0;
        d = C(1,1,1,1,1,1,1); /*last 3 args wrong type */
        return B(B(d)); /* B(d) returns a character-but parameter is of type integer */
    }

fn C(a: int, b: int, c: int, d: int, e: float, f: float, g: float) {
    a=b+c+d;
    e=f+g;
    g = C(1,1,1,1,1.1,1.1,1.1);
}

fn main() {
    let a = 0;

  // a = C(1,2,3,4.0,5.0,6.0); /*calling with 6 args instead of 7*/
  // a = C(1,2,3,4,5.0,6.0,7.0,'a'); /*calling with 8 args instead of 7*/
  a = C(1,2,3,4,5,6,7); /*last 3 args of wrong type*/
  a = C(1,2,3,4,5.0,6.0,b[1]); /*last arg of wrong type*/
  b[1] = B(b[2]); /* error-Parameter to B is of type integer but b[2] is of type character, 2 is out of bounds */
}
